// lib/regionalProductsData.ts

export type Region = "international" | "pakistan" | "gulf" | "chinese";

export interface ProductSeller {
  id: string;
  name: string;
  verified: boolean;
  rating: number;
  reviewCount: number;
  location: string;
  countryCode: string;
  responseRate: string;
}

export interface RegionalProduct {
  id: string;
  title: string;
  slug: string;
  category: string;
  subcategory: string;
  region: Region;
  price: number;
  originalPrice?: number;
  discountPercentage?: number;
  currency: string;
  unit: string;
  moq: number; // Minimum Order Quantity
  image: string;
  gallery?: string[];
  seller: ProductSeller;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  stockQuantity: number;
  deliveryTime: string;
  isPopular?: boolean;
  isFeatured?: boolean;
  tradeAssurance: boolean;
  createdAt: string;
  attributes: Record<string, string>;
}

export const INTERNATIONAL_MOCK_PRODUCTS: RegionalProduct[] = [
  {
    id: "int-101",
    title: "5-Axis High-Precision CNC Milling Machine Center",
    slug: "5-axis-cnc-milling-machine",
    category: "Industrial Machinery",
    subcategory: "CNC Equipment",
    region: "international",
    price: 34500,
    originalPrice: 38000,
    discountPercentage: 9,
    currency: "USD",
    unit: "Unit",
    moq: 1,
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80",
    seller: { id: "s1", name: "Global Industrial Corp", verified: true, rating: 4.9, reviewCount: 142, location: "Stuttgart, Germany", countryCode: "DE", responseRate: "98%" },
    rating: 4.9,
    reviewCount: 42,
    inStock: true,
    stockQuantity: 12,
    deliveryTime: "14-21 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-20T08:00:00Z",
    attributes: { SpindleSpeed: "12000 RPM", Power: "15 kW", Warranty: "2 Years" }
  },
  {
    id: "int-102",
    title: "Automated Micro-Surgical Laser Workstation",
    slug: "micro-surgical-laser-workstation",
    category: "Medical",
    subcategory: "Surgical Equipment",
    region: "international",
    price: 18200,
    originalPrice: 20000,
    discountPercentage: 9,
    currency: "USD",
    unit: "Set",
    moq: 1,
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&q=80",
    seller: { id: "s2", name: "MedTech Precision AG", verified: true, rating: 4.8, reviewCount: 89, location: "Zurich, Switzerland", countryCode: "CH", responseRate: "95%" },
    rating: 4.8,
    reviewCount: 19,
    inStock: true,
    stockQuantity: 5,
    deliveryTime: "10-14 Days",
    isPopular: false,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-22T10:30:00Z",
    attributes: { Certification: "CE / FDA", Wavelength: "1064 nm", Grade: "Medical Class 4" }
  },
  {
    id: "int-103",
    title: "Industrial Robotic Arm 6-Axis Payload 10kg",
    slug: "industrial-robotic-arm-6axis",
    category: "Industrial Machinery",
    subcategory: "Robotics & Automation",
    region: "international",
    price: 12400,
    currency: "USD",
    unit: "Piece",
    moq: 2,
    image: "https://images.unsplash.com/photo-1618042164219-62c820f10723?w=800&q=80",
    seller: { id: "s3", name: "Osaka Automation Co.", verified: true, rating: 4.95, reviewCount: 310, location: "Osaka, Japan", countryCode: "JP", responseRate: "99%" },
    rating: 4.9,
    reviewCount: 78,
    inStock: true,
    stockQuantity: 28,
    deliveryTime: "7-12 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-18T14:20:00Z",
    attributes: { Payload: "10 kg", Reach: "1420 mm", Protection: "IP67" }
  },
  {
    id: "int-104",
    title: "Enterprise Grade AI Edge Server Workstation",
    slug: "enterprise-ai-edge-server",
    category: "Electronics",
    subcategory: "Servers & IT",
    region: "international",
    price: 4800,
    originalPrice: 5500,
    discountPercentage: 12,
    currency: "USD",
    unit: "Unit",
    moq: 1,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80",
    seller: { id: "s4", name: "Silicon Systems Inc", verified: true, rating: 4.7, reviewCount: 64, location: "California, USA", countryCode: "US", responseRate: "92%" },
    rating: 4.7,
    reviewCount: 33,
    inStock: true,
    stockQuantity: 40,
    deliveryTime: "5-8 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: false,
    createdAt: "2026-03-24T09:15:00Z",
    attributes: { RAM: "256 GB DDR5", GPU: "4x Tensor Core", Storage: "8TB NVMe" }
  },
  {
    id: "int-105",
    title: "Commercial Solar Power Inverter 50kW Three Phase",
    slug: "commercial-solar-inverter-50kw",
    category: "Energy & Power",
    subcategory: "Solar Energy",
    region: "international",
    price: 3200,
    currency: "USD",
    unit: "Piece",
    moq: 5,
    image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&q=80",
    seller: { id: "s5", name: "Suntech Energy Global", verified: true, rating: 4.85, reviewCount: 520, location: "Shanghai, China", countryCode: "CN", responseRate: "97%" },
    rating: 4.8,
    reviewCount: 112,
    inStock: true,
    stockQuantity: 150,
    deliveryTime: "15-25 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-10T11:00:00Z",
    attributes: { Efficiency: "98.6%", MaxVoltage: "1100V", Warranty: "10 Years" }
  },
  {
    id: "int-106",
    title: "Heavy-Duty Hydraulic Excavator Bucket Attachment",
    slug: "hydraulic-excavator-bucket-attachment",
    category: "Industrial Machinery",
    subcategory: "Construction Equipment",
    region: "international",
    price: 2100,
    currency: "USD",
    unit: "Piece",
    moq: 1,
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80",
    seller: { id: "s1", name: "Global Industrial Corp", verified: true, rating: 4.9, reviewCount: 142, location: "Stuttgart, Germany", countryCode: "DE", responseRate: "98%" },
    rating: 4.6,
    reviewCount: 22,
    inStock: false,
    stockQuantity: 0,
    deliveryTime: "30 Days (On Order)",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-02-15T16:45:00Z",
    attributes: { Capacity: "1.2 m3", SteelGrade: "Hardox 450", Weight: "850 kg" }
  },
  {
    id: "int-107",
    title: "Portable Ultrasound Imaging Diagnostic System",
    slug: "portable-ultrasound-imaging-system",
    category: "Medical",
    subcategory: "Diagnostic Devices",
    region: "international",
    price: 6400,
    originalPrice: 7200,
    discountPercentage: 11,
    currency: "USD",
    unit: "Unit",
    moq: 1,
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&q=80",
    seller: { id: "s2", name: "MedTech Precision AG", verified: true, rating: 4.8, reviewCount: 89, location: "Zurich, Switzerland", countryCode: "CH", responseRate: "95%" },
    rating: 4.9,
    reviewCount: 54,
    inStock: true,
    stockQuantity: 18,
    deliveryTime: "7-10 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-21T12:00:00Z",
    attributes: { Screen: "15.6 inch HD Touch", ProbeTypes: "Convex / Linear", Battery: "4 Hours" }
  },
  {
    id: "int-108",
    title: "Automated SMT Pick and Place PCB Assembly Machine",
    slug: "smt-pick-and-place-pcb-machine",
    category: "Electronics",
    subcategory: "Manufacturing Tech",
    region: "international",
    price: 22800,
    currency: "USD",
    unit: "Set",
    moq: 1,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    seller: { id: "s3", name: "Osaka Automation Co.", verified: true, rating: 4.95, reviewCount: 310, location: "Osaka, Japan", countryCode: "JP", responseRate: "99%" },
    rating: 4.95,
    reviewCount: 91,
    inStock: true,
    stockQuantity: 4,
    deliveryTime: "14-20 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-25T07:10:00Z",
    attributes: { Speed: "15000 CPH", Feeders: "64 Slots", Precision: "0.01 mm" }
  },

  // --- Added: more subcategories on existing categories ---
  {
    id: "int-109",
    title: "Automatic Carton Box Packaging Machine",
    slug: "automatic-carton-box-packaging-machine",
    category: "Industrial Machinery",
    subcategory: "Packaging Machinery",
    region: "international",
    price: 15600,
    originalPrice: 17200,
    discountPercentage: 9,
    currency: "USD",
    unit: "Set",
    moq: 1,
    image: "https://picsum.photos/seed/automatic-carton-box-packaging-machine/800/600",
    seller: { id: "s6", name: "Nordic PackTech AB", verified: true, rating: 4.75, reviewCount: 118, location: "Gothenburg, Sweden", countryCode: "SE", responseRate: "94%" },
    rating: 4.75,
    reviewCount: 37,
    inStock: true,
    stockQuantity: 9,
    deliveryTime: "18-25 Days",
    isPopular: false,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-04-02T09:00:00Z",
    attributes: { Speed: "40 Boxes/Min", BoxSize: "Adjustable", Power: "6.5 kW" }
  },
  {
    id: "int-110",
    title: "Electric Wheelchair with Powered Recline",
    slug: "electric-wheelchair-powered-recline",
    category: "Medical",
    subcategory: "Rehabilitation Equipment",
    region: "international",
    price: 2350,
    currency: "USD",
    unit: "Piece",
    moq: 2,
    image: "https://picsum.photos/seed/electric-wheelchair-powered-recline/800/600",
    seller: { id: "s2", name: "MedTech Precision AG", verified: true, rating: 4.8, reviewCount: 89, location: "Zurich, Switzerland", countryCode: "CH", responseRate: "95%" },
    rating: 4.7,
    reviewCount: 28,
    inStock: true,
    stockQuantity: 60,
    deliveryTime: "10-16 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-03T10:20:00Z",
    attributes: { BatteryRange: "25 km", MaxLoad: "150 kg", FoldableFrame: "Yes" }
  },
  {
    id: "int-115",
    title: "High-Speed Circular Knitting Textile Machine",
    slug: "high-speed-circular-knitting-textile-machine",
    category: "Industrial Machinery",
    subcategory: "Textile Machinery",
    region: "international",
    price: 28900,
    currency: "USD",
    unit: "Unit",
    moq: 1,
    image: "https://picsum.photos/seed/circular-knitting-textile-machine/800/600",
    seller: { id: "s9", name: "Anatolia Textile Machinery", verified: true, rating: 4.7, reviewCount: 76, location: "Bursa, Turkey", countryCode: "TR", responseRate: "93%" },
    rating: 4.7,
    reviewCount: 21,
    inStock: true,
    stockQuantity: 6,
    deliveryTime: "20-28 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-07T08:20:00Z",
    attributes: { Gauge: "28 GG", Diameter: "34 Inch", Speed: "0.85 rpm/inch" }
  },
  {
    id: "int-116",
    title: "Bulk Automotive-Grade MLCC Capacitor Reels",
    slug: "bulk-automotive-grade-mlcc-capacitor-reels",
    category: "Electronics",
    subcategory: "Consumer Electronics Components",
    region: "international",
    price: 0.018,
    currency: "USD",
    unit: "Piece",
    moq: 500000,
    image: "https://picsum.photos/seed/mlcc-capacitor-reels/800/600",
    seller: { id: "s4", name: "Silicon Systems Inc", verified: true, rating: 4.7, reviewCount: 64, location: "California, USA", countryCode: "US", responseRate: "92%" },
    rating: 4.6,
    reviewCount: 15,
    inStock: true,
    stockQuantity: 8000000,
    deliveryTime: "10-15 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: false,
    createdAt: "2026-04-08T09:30:00Z",
    attributes: { Capacitance: "10 µF", Voltage: "25V", Case: "0805" }
  },
  {
    id: "int-117",
    title: "Onshore Wind Turbine Blade Assembly 3MW",
    slug: "onshore-wind-turbine-blade-assembly-3mw",
    category: "Energy & Power",
    subcategory: "Wind Energy",
    region: "international",
    price: 48000,
    currency: "USD",
    unit: "Set",
    moq: 1,
    image: "https://picsum.photos/seed/wind-turbine-blade-assembly/800/600",
    seller: { id: "s5", name: "Suntech Energy Global", verified: true, rating: 4.85, reviewCount: 520, location: "Shanghai, China", countryCode: "CN", responseRate: "97%" },
    rating: 4.8,
    reviewCount: 17,
    inStock: true,
    stockQuantity: 3,
    deliveryTime: "30-45 Days",
    isPopular: false,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-04-09T10:00:00Z",
    attributes: { RatedPower: "3 MW", BladeLength: "62 m", Material: "Glass-Fiber Composite" }
  },

  // --- Added: brand-new categories ---
  {
    id: "int-111",
    title: "Heavy-Duty Truck Diesel Engine Long Block",
    slug: "heavy-duty-truck-diesel-engine-long-block",
    category: "Automotive & Transport",
    subcategory: "Truck Engine Parts",
    region: "international",
    price: 8900,
    originalPrice: 9800,
    discountPercentage: 9,
    currency: "USD",
    unit: "Unit",
    moq: 1,
    image: "https://picsum.photos/seed/heavy-duty-truck-diesel-engine/800/600",
    seller: { id: "s7", name: "Continental Diesel Parts", verified: true, rating: 4.6, reviewCount: 203, location: "Detroit, USA", countryCode: "US", responseRate: "93%" },
    rating: 4.6,
    reviewCount: 61,
    inStock: true,
    stockQuantity: 22,
    deliveryTime: "12-18 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-01T08:30:00Z",
    attributes: { Displacement: "12.8 L", Cylinders: "6", Emission: "Euro 5" }
  },
  {
    id: "int-112",
    title: "Electric Vehicle Fast-Charging Station 120kW",
    slug: "ev-fast-charging-station-120kw",
    category: "Automotive & Transport",
    subcategory: "EV Charging Infrastructure",
    region: "international",
    price: 21500,
    currency: "USD",
    unit: "Unit",
    moq: 1,
    image: "https://picsum.photos/seed/ev-fast-charging-station/800/600",
    seller: { id: "s5", name: "Suntech Energy Global", verified: true, rating: 4.85, reviewCount: 520, location: "Shanghai, China", countryCode: "CN", responseRate: "97%" },
    rating: 4.85,
    reviewCount: 44,
    inStock: true,
    stockQuantity: 15,
    deliveryTime: "20-30 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-04-04T13:00:00Z",
    attributes: { OutputPower: "120 kW", Connectors: "CCS2 / CHAdeMO", Cooling: "Liquid-Cooled" }
  },
  {
    id: "int-113",
    title: "Industrial Grade Epoxy Resin Coating Compound",
    slug: "industrial-epoxy-resin-coating-compound",
    category: "Chemicals & Materials",
    subcategory: "Industrial Coatings",
    region: "international",
    price: 62,
    currency: "USD",
    unit: "Drum (200L)",
    moq: 10,
    image: "https://picsum.photos/seed/industrial-epoxy-resin-coating/800/600",
    seller: { id: "s8", name: "Rhine Chemical Works", verified: true, rating: 4.7, reviewCount: 96, location: "Cologne, Germany", countryCode: "DE", responseRate: "95%" },
    rating: 4.7,
    reviewCount: 25,
    inStock: true,
    stockQuantity: 400,
    deliveryTime: "10-15 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-05T09:45:00Z",
    attributes: { CureTime: "24 Hours", Application: "Flooring / Marine", VOC: "Low VOC" }
  },
  {
    id: "int-114",
    title: "High-Purity Industrial Silicone Sealant Bulk Pack",
    slug: "high-purity-industrial-silicone-sealant",
    category: "Chemicals & Materials",
    subcategory: "Sealants & Adhesives",
    region: "international",
    price: 4.2,
    currency: "USD",
    unit: "Tube",
    moq: 2000,
    image: "https://picsum.photos/seed/industrial-silicone-sealant/800/600",
    seller: { id: "s8", name: "Rhine Chemical Works", verified: true, rating: 4.7, reviewCount: 96, location: "Cologne, Germany", countryCode: "DE", responseRate: "95%" },
    rating: 4.6,
    reviewCount: 18,
    inStock: true,
    stockQuantity: 50000,
    deliveryTime: "15-22 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-06T11:10:00Z",
    attributes: { Type: "Neutral Cure Silicone", Temperature_Range: "-40°C to 200°C", Color: "Clear / White / Black" }
  }
];



export const REGIONAL_MOCK_PRODUCTS: RegionalProduct[] = [
  {
    id: "pk-101",
    title: "Premium Pakistani Leather Wallet",
    slug: "premium-pakistani-leather-wallet",
    category: "Leather Products",
    subcategory: "Wallets",
    region: "pakistan",
    price: 18,
    originalPrice: 22,
    discountPercentage: 18,
    currency: "USD",
    unit: "Piece",
    moq: 50,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80",
    seller: {
      id: "pk-s1",
      name: "Sialkot Leather Exports",
      verified: true,
      rating: 4.8,
      reviewCount: 126,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "97%"
    },
    rating: 4.8,
    reviewCount: 126,
    inStock: true,
    stockQuantity: 2500,
    deliveryTime: "5-10 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-20T08:00:00Z",
    attributes: {
      Material: "Genuine Cow Leather",
      Color: "Brown",
      Size: "Standard",
      Finish: "Premium"
    }
  },
  {
    id: "pk-102",
    title: "Professional Surgical Instruments Set",
    slug: "professional-surgical-instruments-set",
    category: "Medical",
    subcategory: "Surgical Instruments",
    region: "pakistan",
    price: 145,
    currency: "USD",
    unit: "Set",
    moq: 10,
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&q=80",
    seller: {
      id: "pk-s2",
      name: "Sialkot Surgical Industries",
      verified: true,
      rating: 4.9,
      reviewCount: 218,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "99%"
    },
    rating: 4.9,
    reviewCount: 218,
    inStock: true,
    stockQuantity: 850,
    deliveryTime: "7-14 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-21T09:00:00Z",
    attributes: {
      Material: "Stainless Steel",
      Certification: "ISO 13485",
      Finish: "Surgical Grade",
      Packaging: "Sterile Packaging"
    }
  },
  {
    id: "pk-103",
    title: "Premium Pakistani Lawn Cotton Fabric",
    slug: "premium-pakistani-lawn-cotton-fabric",
    category: "Textiles",
    subcategory: "Lawn Fabric",
    region: "pakistan",
    price: 6.5,
    currency: "USD",
    unit: "Meter",
    moq: 500,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    seller: {
      id: "pk-s3",
      name: "Lahore Textile Mills",
      verified: true,
      rating: 4.7,
      reviewCount: 164,
      location: "Lahore, Pakistan",
      countryCode: "PK",
      responseRate: "96%"
    },
    rating: 4.7,
    reviewCount: 164,
    inStock: true,
    stockQuantity: 25000,
    deliveryTime: "10-15 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-18T11:00:00Z",
    attributes: {
      Material: "100% Cotton",
      Width: "44 Inches",
      Weight: "80 GSM",
      Pattern: "Printed"
    }
  },
  {
    id: "pk-104",
    title: "Handcrafted Pakistani Sports Gloves",
    slug: "handcrafted-pakistani-sports-gloves",
    category: "Sports & Fitness",
    subcategory: "Sports Gloves",
    region: "pakistan",
    price: 12,
    currency: "USD",
    unit: "Pair",
    moq: 100,
    image: "https://images.unsplash.com/photo-1583473848882-f9a5f493a3d7?w=800&q=80",
    seller: {
      id: "pk-s4",
      name: "Punjab Sports Manufacturing",
      verified: true,
      rating: 4.8,
      reviewCount: 94,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "98%"
    },
    rating: 4.8,
    reviewCount: 94,
    inStock: true,
    stockQuantity: 5000,
    deliveryTime: "7-12 Days",
    isPopular: false,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-22T13:00:00Z",
    attributes: {
      Material: "Premium Synthetic Leather",
      Size: "S / M / L / XL",
      Usage: "Sports & Training",
      Customization: "Available"
    }
  },
  {
    id: "pk-105",
    title: "Premium Pakistani Cotton T-Shirts",
    slug: "premium-pakistani-cotton-t-shirts",
    category: "Apparel",
    subcategory: "T-Shirts",
    region: "pakistan",
    price: 7.5,
    currency: "USD",
    unit: "Piece",
    moq: 100,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
    seller: {
      id: "pk-s5",
      name: "Faisalabad Garments Export",
      verified: true,
      rating: 4.8,
      reviewCount: 187,
      location: "Faisalabad, Pakistan",
      countryCode: "PK",
      responseRate: "97%"
    },
    rating: 4.8,
    reviewCount: 187,
    inStock: true,
    stockQuantity: 12000,
    deliveryTime: "12-18 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-24T10:00:00Z",
    attributes: {
      Material: "100% Combed Cotton",
      Weight: "180 GSM",
      Sizes: "S / M / L / XL / XXL",
      Customization: "Private Label Available"
    }
  },
  {
    id: "pk-106",
    title: "Natural Himalayan Pink Salt Lamp",
    slug: "natural-himalayan-pink-salt-lamp",
    category: "Home & Decor",
    subcategory: "Lighting",
    region: "pakistan",
    price: 14,
    originalPrice: 18,
    discountPercentage: 22,
    currency: "USD",
    unit: "Piece",
    moq: 200,
    image: "https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?w=800&q=80",
    seller: {
      id: "pk-s6",
      name: "Khewra Salt Crafts",
      verified: true,
      rating: 4.9,
      reviewCount: 310,
      location: "Jhelum, Pakistan",
      countryCode: "PK",
      responseRate: "99%"
    },
    rating: 4.9,
    reviewCount: 310,
    inStock: true,
    stockQuantity: 15000,
    deliveryTime: "14-21 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-25T11:00:00Z",
    attributes: {
      Material: "100% Pure Himalayan Salt",
      Weight: "3-5 kg",
      Base: "Neem Wood",
      Voltage: "110V - 240V"
    }
  },
  {
    id: "pk-107",
    title: "Match Grade Leather Cricket Balls",
    slug: "match-grade-leather-cricket-balls",
    category: "Sports & Fitness",
    subcategory: "Cricket Gear",
    region: "pakistan",
    price: 8.5,
    currency: "USD",
    unit: "Piece",
    moq: 120,
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80",
    seller: {
      id: "pk-s4",
      name: "Punjab Sports Manufacturing",
      verified: true,
      rating: 4.8,
      reviewCount: 94,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "98%"
    },
    rating: 4.7,
    reviewCount: 82,
    inStock: true,
    stockQuantity: 4000,
    deliveryTime: "7-10 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-15T09:30:00Z",
    attributes: {
      Core: "Layered Cork & Wool",
      Cover: "Alum Tanned Leather",
      Weight: "156g (5.5 oz)",
      Seam: "Hand Stitched"
    }
  },
  {
    id: "pk-108",
    title: "Handcrafted Onyx Marble Bowl",
    slug: "handcrafted-onyx-marble-bowl",
    category: "Home & Decor",
    subcategory: "Handicrafts",
    region: "pakistan",
    price: 35,
    originalPrice: 45,
    discountPercentage: 22,
    currency: "USD",
    unit: "Piece",
    moq: 30,
    image: "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&q=80",
    seller: {
      id: "pk-s7",
      name: "Balochistan Minerals & Stone",
      verified: true,
      rating: 4.6,
      reviewCount: 52,
      location: "Quetta, Pakistan",
      countryCode: "PK",
      responseRate: "92%"
    },
    rating: 4.6,
    reviewCount: 52,
    inStock: true,
    stockQuantity: 300,
    deliveryTime: "10-20 Days",
    isPopular: false,
    isFeatured: true,
    tradeAssurance: false,
    createdAt: "2026-03-10T14:15:00Z",
    attributes: {
      Material: "Green Onyx Marble",
      Diameter: "8 Inches",
      Finish: "Polished",
      Origin: "Chagai, Balochistan"
    }
  },
  {
    id: "pk-109",
    title: "Heavy Duty Raw Denim Jeans",
    slug: "heavy-duty-raw-denim-jeans",
    category: "Apparel",
    subcategory: "Denim",
    region: "pakistan",
    price: 19.5,
    currency: "USD",
    unit: "Piece",
    moq: 200,
    image: "https://images.unsplash.com/photo-1542272604-780c36856842?w=800&q=80",
    seller: {
      id: "pk-s8",
      name: "Karachi Textile & Denim Mills",
      verified: true,
      rating: 4.9,
      reviewCount: 412,
      location: "Karachi, Pakistan",
      countryCode: "PK",
      responseRate: "98%"
    },
    rating: 4.9,
    reviewCount: 412,
    inStock: true,
    stockQuantity: 18000,
    deliveryTime: "15-25 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-23T16:00:00Z",
    attributes: {
      Material: "14oz Selvedge Denim",
      Fit: "Regular Straight",
      Wash: "Raw Unwashed",
      Hardware: "Brass Rivets"
    }
  },
  {
    id: "pk-110",
    title: "Hand-Forged Damascus Steel Chef Knife",
    slug: "hand-forged-damascus-steel-chef-knife",
    category: "Cutlery",
    subcategory: "Kitchen Knives",
    region: "pakistan",
    price: 48,
    originalPrice: 60,
    discountPercentage: 20,
    currency: "USD",
    unit: "Piece",
    moq: 20,
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80",
    seller: {
      id: "pk-s9",
      name: "Wazirabad Blade Artisans",
      verified: true,
      rating: 4.8,
      reviewCount: 145,
      location: "Wazirabad, Pakistan",
      countryCode: "PK",
      responseRate: "95%"
    },
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    stockQuantity: 600,
    deliveryTime: "8-12 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-19T08:45:00Z",
    attributes: {
      Blade: "1095 & 15N20 Damascus (256 Layers)",
      Handle: "Rosewood & Brass Pins",
      Overall_Length: "12 Inches",
      Hardness: "58-60 HRC"
    }
  },
  {
    id: "pk-111",
    title: "Organic Basmati Rice (1121 Extra Long Grain)",
    slug: "organic-basmati-rice-1121-extra-long-grain",
    category: "Agriculture",
    subcategory: "Grains & Rice",
    region: "pakistan",
    price: 1.25,
    currency: "USD",
    unit: "Kg",
    moq: 1000,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&q=80",
    seller: {
      id: "pk-s10",
      name: "Punjab Agri Exports",
      verified: true,
      rating: 4.7,
      reviewCount: 89,
      location: "Gujranwala, Pakistan",
      countryCode: "PK",
      responseRate: "94%"
    },
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    stockQuantity: 100000,
    deliveryTime: "15-30 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-12T12:00:00Z",
    attributes: {
      Purity: "95%",
      Average_Grain_Length: "8.35 mm",
      Moisture: "12% Max",
      Crop_Year: "2025/2026"
    }
  },
  {
    id: "pk-112",
    title: "Hand-Knotted Woolen Chobi Area Rug",
    slug: "hand-knotted-woolen-chobi-area-rug",
    category: "Home & Decor",
    subcategory: "Carpets & Rugs",
    region: "pakistan",
    price: 320,
    currency: "USD",
    unit: "Piece",
    moq: 2,
    image: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800&q=80",
    seller: {
      id: "pk-s11",
      name: "Peshawar Carpet Guild",
      verified: true,
      rating: 5.0,
      reviewCount: 38,
      location: "Peshawar, Pakistan",
      countryCode: "PK",
      responseRate: "100%"
    },
    rating: 5.0,
    reviewCount: 38,
    inStock: true,
    stockQuantity: 45,
    deliveryTime: "10-18 Days",
    isPopular: false,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-05T07:20:00Z",
    attributes: {
      Material: "Hand-spun Ghazni Wool",
      Dye: "Natural Vegetable Dyes",
      Size: "5ft x 8ft",
      Knot_Density: "120 KPSI"
    }
  },
  {
    id: "pk-113",
    title: "Heavy Duty BJJ Jiu-Jitsu Gi",
    slug: "heavy-duty-bjj-jiu-jitsu-gi",
    category: "Sports & Fitness",
    subcategory: "Martial Arts Equipment",
    region: "pakistan",
    price: 32,
    currency: "USD",
    unit: "Suit",
    moq: 50,
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80",
    seller: {
      id: "pk-s4",
      name: "Punjab Sports Manufacturing",
      verified: true,
      rating: 4.8,
      reviewCount: 94,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "98%"
    },
    rating: 4.8,
    reviewCount: 76,
    inStock: true,
    stockQuantity: 1200,
    deliveryTime: "10-14 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-17T15:10:00Z",
    attributes: {
      Jacket_Weave: "450 GSM Pearl Weave",
      Pants: "10oz Ripstop Cotton",
      Shrinkage: "Pre-shrunk Fabric",
      Colors: "White / Blue / Black"
    }
  },
  {
    id: "pk-114",
    title: "Pure Raw Sidr Honey",
    slug: "pure-raw-sidr-honey",
    category: "Agriculture",
    subcategory: "Organic Foods",
    region: "pakistan",
    price: 24,
    originalPrice: 28,
    discountPercentage: 14,
    currency: "USD",
    unit: "Kg",
    moq: 25,
    image: "https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=800&q=80",
    seller: {
      id: "pk-s12",
      name: "Karak Organic Honey Apiaries",
      verified: true,
      rating: 4.9,
      reviewCount: 110,
      location: "Karak, Pakistan",
      countryCode: "PK",
      responseRate: "96%"
    },
    rating: 4.9,
    reviewCount: 110,
    inStock: true,
    stockQuantity: 3500,
    deliveryTime: "7-12 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-03-21T18:30:00Z",
    attributes: {
      Source: "Wild Sidr Trees (Wild Badr)",
      Processing: "Raw, Unfiltered, Unheated",
      Testing: "Lab Certified 100% Pure",
      Packaging: "Food-grade Glass Jars"
    }
  },
  {
    id: "pk-115",
    title: "Custom Embroidered Leather Biker Jacket",
    slug: "custom-embroidered-leather-biker-jacket",
    category: "Leather Products",
    subcategory: "Jackets",
    region: "pakistan",
    price: 78,
    currency: "USD",
    unit: "Piece",
    moq: 15,
    image: "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=800&q=80",
    seller: {
      id: "pk-s1",
      name: "Sialkot Leather Exports",
      verified: true,
      rating: 4.8,
      reviewCount: 126,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "97%"
    },
    rating: 4.8,
    reviewCount: 126,
    inStock: true,
    stockQuantity: 400,
    deliveryTime: "12-20 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-03-24T11:40:00Z",
    attributes: {
      Material: "100% Sheepskin Leather",
      Lining: "Polyester Satin",
      Zippers: "YKK Original",
      Customization: "Custom Embroidery & Badges"
    }
  },

  // --- Added: more subcategories on existing categories ---
  {
    id: "pk-116",
    title: "Professional Adjustable Dumbbell Set",
    slug: "professional-adjustable-dumbbell-set",
    category: "Sports & Fitness",
    subcategory: "Gym Equipment",
    region: "pakistan",
    price: 42,
    originalPrice: 55,
    discountPercentage: 24,
    currency: "USD",
    unit: "Set",
    moq: 30,
    image: "https://picsum.photos/seed/professional-adjustable-dumbbell-set/800/600",
    seller: {
      id: "pk-s4",
      name: "Punjab Sports Manufacturing",
      verified: true,
      rating: 4.8,
      reviewCount: 94,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "98%"
    },
    rating: 4.7,
    reviewCount: 41,
    inStock: true,
    stockQuantity: 900,
    deliveryTime: "10-16 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-01T09:00:00Z",
    attributes: { WeightRange: "5-25 kg", Coating: "Rubber-Encased", Adjustment: "Dial System" }
  },
  {
    id: "pk-117",
    title: "Handmade Sheesham Wood Dining Table Set",
    slug: "handmade-sheesham-wood-dining-table-set",
    category: "Home & Decor",
    subcategory: "Wooden Furniture",
    region: "pakistan",
    price: 285,
    currency: "USD",
    unit: "Set",
    moq: 3,
    image: "https://picsum.photos/seed/handmade-sheesham-wood-dining-table/800/600",
    seller: {
      id: "pk-s13",
      name: "Chiniot Woodcraft Exports",
      verified: true,
      rating: 4.9,
      reviewCount: 67,
      location: "Chiniot, Pakistan",
      countryCode: "PK",
      responseRate: "96%"
    },
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    stockQuantity: 25,
    deliveryTime: "20-30 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-04-02T10:15:00Z",
    attributes: { Material: "Solid Sheesham Wood", Seats: "6-Seater", Finish: "Hand-Carved Walnut", Assembly: "Flat-Pack" }
  },
  {
    id: "pk-122",
    title: "Hand-Embroidered Chikankari Fabric Bundle",
    slug: "hand-embroidered-chikankari-fabric-bundle",
    category: "Textiles",
    subcategory: "Embroidered Fabric",
    region: "pakistan",
    price: 11,
    originalPrice: 14,
    discountPercentage: 21,
    currency: "USD",
    unit: "Meter",
    moq: 300,
    image: "https://picsum.photos/seed/chikankari-embroidered-fabric/800/600",
    seller: {
      id: "pk-s3",
      name: "Lahore Textile Mills",
      verified: true,
      rating: 4.7,
      reviewCount: 164,
      location: "Lahore, Pakistan",
      countryCode: "PK",
      responseRate: "96%"
    },
    rating: 4.7,
    reviewCount: 33,
    inStock: true,
    stockQuantity: 9000,
    deliveryTime: "12-18 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-07T09:10:00Z",
    attributes: { Material: "Cotton / Lawn Base", Technique: "Hand Chikankari", Width: "44 Inches", Pattern: "Floral" }
  },
  {
    id: "pk-123",
    title: "Premium Dried Apricots & Mixed Nuts Bulk Pack",
    slug: "premium-dried-apricots-mixed-nuts-bulk",
    category: "Agriculture",
    subcategory: "Dried Fruits & Nuts",
    region: "pakistan",
    price: 5.8,
    currency: "USD",
    unit: "Kg",
    moq: 500,
    image: "https://picsum.photos/seed/dried-apricots-mixed-nuts/800/600",
    seller: {
      id: "pk-s10",
      name: "Punjab Agri Exports",
      verified: true,
      rating: 4.7,
      reviewCount: 89,
      location: "Gujranwala, Pakistan",
      countryCode: "PK",
      responseRate: "94%"
    },
    rating: 4.6,
    reviewCount: 27,
    inStock: true,
    stockQuantity: 12000,
    deliveryTime: "12-20 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-08T10:40:00Z",
    attributes: { Origin: "Gilgit-Baltistan / Chitral", Grade: "Export Grade A", Processing: "Sun-Dried", Packaging: "Vacuum Sealed" }
  },
  {
    id: "pk-124",
    title: "Surgical Grade Stainless Steel Barber Scissors",
    slug: "surgical-grade-stainless-steel-barber-scissors",
    category: "Cutlery",
    subcategory: "Scissors & Shears",
    region: "pakistan",
    price: 6.2,
    originalPrice: 8,
    discountPercentage: 22,
    currency: "USD",
    unit: "Piece",
    moq: 100,
    image: "https://picsum.photos/seed/barber-scissors-stainless-steel/800/600",
    seller: {
      id: "pk-s2",
      name: "Sialkot Surgical Industries",
      verified: true,
      rating: 4.9,
      reviewCount: 218,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "99%"
    },
    rating: 4.8,
    reviewCount: 45,
    inStock: true,
    stockQuantity: 6000,
    deliveryTime: "8-14 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-09T11:20:00Z",
    attributes: { Material: "440C Stainless Steel", BladeLength: "5.5 Inches", Handle: "Offset Ergonomic", Finish: "Mirror Polished" }
  },

  // --- Added: brand-new categories ---
  {
    id: "pk-118",
    title: "Handmade Genuine Leather Formal Shoes",
    slug: "handmade-genuine-leather-formal-shoes",
    category: "Footwear",
    subcategory: "Formal Shoes",
    region: "pakistan",
    price: 22,
    originalPrice: 28,
    discountPercentage: 21,
    currency: "USD",
    unit: "Pair",
    moq: 100,
    image: "https://picsum.photos/seed/handmade-leather-formal-shoes/800/600",
    seller: {
      id: "pk-s1",
      name: "Sialkot Leather Exports",
      verified: true,
      rating: 4.8,
      reviewCount: 126,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "97%"
    },
    rating: 4.7,
    reviewCount: 58,
    inStock: true,
    stockQuantity: 3000,
    deliveryTime: "10-15 Days",
    isPopular: true,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-03T08:00:00Z",
    attributes: { Material: "Full-Grain Leather", Sole: "Goodyear Welted", Sizes: "EU 39-46", Customization: "Private Label" }
  },
  {
    id: "pk-119",
    title: "Handwoven Leather Sports Sandals",
    slug: "handwoven-leather-sports-sandals",
    category: "Footwear",
    subcategory: "Sandals & Chappals",
    region: "pakistan",
    price: 9.5,
    currency: "USD",
    unit: "Pair",
    moq: 150,
    image: "https://picsum.photos/seed/handwoven-leather-sports-sandals/800/600",
    seller: {
      id: "pk-s1",
      name: "Sialkot Leather Exports",
      verified: true,
      rating: 4.8,
      reviewCount: 126,
      location: "Sialkot, Pakistan",
      countryCode: "PK",
      responseRate: "97%"
    },
    rating: 4.6,
    reviewCount: 34,
    inStock: true,
    stockQuantity: 5000,
    deliveryTime: "8-12 Days",
    isPopular: false,
    isFeatured: false,
    tradeAssurance: true,
    createdAt: "2026-04-04T11:30:00Z",
    attributes: { Material: "Genuine Buffalo Leather", Sole: "Rubber", Style: "Peshawari Chappal", Sizes: "EU 38-45" }
  },
  {
    id: "pk-120",
    title: "Natural Peshawar Emerald Gemstone (Loose)",
    slug: "natural-peshawar-emerald-gemstone",
    category: "Jewelry & Gemstones",
    subcategory: "Precious Stones",
    region: "pakistan",
    price: 65,
    currency: "USD",
    unit: "Carat",
    moq: 5,
    image: "https://picsum.photos/seed/natural-peshawar-emerald-gemstone/800/600",
    seller: {
      id: "pk-s14",
      name: "Swat Valley Gemstones",
      verified: true,
      rating: 4.8,
      reviewCount: 73,
      location: "Mingora, Pakistan",
      countryCode: "PK",
      responseRate: "94%"
    },
    rating: 4.8,
    reviewCount: 73,
    inStock: true,
    stockQuantity: 800,
    deliveryTime: "10-18 Days",
    isPopular: true,
    isFeatured: true,
    tradeAssurance: false,
    createdAt: "2026-04-05T12:00:00Z",
    attributes: { Origin: "Swat Valley, Pakistan", Clarity: "Eye Clean", Cut: "Emerald / Oval", Certification: "Gemological Report Available" }
  },
  {
    id: "pk-121",
    title: "Sterling Silver Kundan Jewelry Set",
    slug: "sterling-silver-kundan-jewelry-set",
    category: "Jewelry & Gemstones",
    subcategory: "Silver Jewelry",
    region: "pakistan",
    price: 38,
    originalPrice: 48,
    discountPercentage: 21,
    currency: "USD",
    unit: "Set",
    moq: 20,
    image: "https://picsum.photos/seed/sterling-silver-kundan-jewelry/800/600",
    seller: {
      id: "pk-s14",
      name: "Swat Valley Gemstones",
      verified: true,
      rating: 4.8,
      reviewCount: 73,
      location: "Mingora, Pakistan",
      countryCode: "PK",
      responseRate: "94%"
    },
    rating: 4.7,
    reviewCount: 29,
    inStock: true,
    stockQuantity: 600,
    deliveryTime: "12-20 Days",
    isPopular: false,
    isFeatured: true,
    tradeAssurance: true,
    createdAt: "2026-04-06T09:20:00Z",
    attributes: { Material: "925 Sterling Silver", Style: "Kundan / Meenakari", Pieces: "Necklace + Earrings", Plating: "Rhodium" }
  }
];